[package]
name = "gh-enterprise-tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
octocrab = "0.32.0"
tokio = { version = "1.34.0", features = ["rt-multi-thread", "macros"] }
